version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: gatus
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gatus
    restart: unless-stopped

  gatus:
    build: .
    image: liam1010/gatus-custom:latest
    volumes:
      - ./config:/config
    ports:
      - "8080:8080"
    environment:
      POSTGRES_USER: gatus
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gatus
      POSTGRES_HOST: postgres
    depends_on:
      - postgres
    restart: unless-stopped