storage:
  type: postgres
  path: "postgres://gatus:password@postgres:5432/gatus?sslmode=disable"
endpoints:
  # Monitor
  - name: Prometheus
    group: Monitor
    url: "https://www.instagram.com"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: email
        enabled: true
        description: "healthcheck failed"
        send-on-resolved: true

alerting:
  email:
    from: "user1@example.com"
    host: "smtp.mediatek.inc"
    username: "srv_it_eas1_tester@xxxxxx"
    password: "your_password"
    port: 25
    to: "user2@example.com"
